export const testEmployeesData = [
  {
    id: "1",
    firstName: "John",
    lastName: "Janvier",
    dateOfBirth: "1990-01-01",
    startDate: "2020-01-01",
    department: "Engineering",
    street: "123 Main St",
    city: "Anytown",
    state: "CA",
    zipCode: 12345,
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Février",
    dateOfBirth: "1980-01-01",
    startDate: "2022-02-01",
    department: "Computer Scientist",
    street: "234 Main St",
    city: "Anytown",
    state: "CA",
    zipCode: 54321,
  },
  {
    id: "3",
    firstName: "Anne",
    lastName: "Mars",
    dateOfBirth: "1978-08-12",
    startDate: "2023-02-05",
    department: "Computer Scientist",
    street: "345 Main St",
    city: "Anytown",
    state: "CA",
    zipCode: 54321,
  },
  {
    id: "4",
    firstName: "Jean",
    lastName: "Avril",
    dateOfBirth: "1988-01-01",
    startDate: "2020-02-01",
    department: "Computer Scientist",
    street: "456 Main St",
    city: "Anytown",
    state: "CA",
    zipCode: 54321,
  },
  {
    id: "5",
    firstName: "Pascal",
    lastName: "Mai",
    dateOfBirth: "1980-01-01",
    startDate: "2017-02-01",
    department: "Computer Scientist",
    street: "567 Main St",
    city: "Anytown",
    state: "CO",
    zipCode: 54321,
  },
  {
    id: "6",
    firstName: "Lilou",
    lastName: "Juin",
    dateOfBirth: "1980-01-01",
    startDate: "2024-02-01",
    department: "Computer Scientist",
    street: "678 Main St",
    city: "Anytown",
    state: "CT",
    zipCode: 54321,
  },
  {
    id: "7",
    firstName: "Willow",
    lastName: "Juillet",
    dateOfBirth: "1980-01-01",
    startDate: "2002-02-01",
    department: "Computer Scientist",
    street: "789 Main St",
    city: "Anytown",
    state: "DE",
    zipCode: 54321,
  },
  {
    id: "8",
    firstName: "Milo",
    lastName: "Aout",
    dateOfBirth: "1980-01-01",
    startDate: "2003-02-01",
    department: "Computer Scientist",
    street: "987 Main St",
    city: "Anytown",
    state: "DC",
    zipCode: 54321,
  },
  {
    id: "9",
    firstName: "Noe",
    lastName: "Septembre",
    dateOfBirth: "1980-01-01",
    startDate: "2012-02-01",
    department: "Computer Scientist",
    street: "876 Main St",
    city: "Anytown",
    state: "CA",
    zipCode: 54321,
  },
  {
    id: "10",
    firstName: "Rose",
    lastName: "Octobre",
    dateOfBirth: "1980-01-01",
    startDate: "2006-02-01",
    department: "Computer Scientist",
    street: "765 Main St",
    city: "Anytown",
    state: "Al",
    zipCode: 54321,
  },
  {
    id: "11",
    firstName: "Marie",
    lastName: "Novembre",
    dateOfBirth: "1980-01-01",
    startDate: "2006-03-01",
    department: "Computer Scientist",
    street: "654 Main St",
    city: "Anytown",
    state: "AK",
    zipCode: 54321,
  },
  {
    id: "12",
    firstName: "Guillaume",
    lastName: "Décembre",
    dateOfBirth: "1980-01-01",
    startDate: "2000-02-01",
    department: "Computer Scientist",
    street: "543 Main St",
    city: "Anytown",
    state: "AZ",
    zipCode: 54321,
  },
]

export const states: { name: string; abbreviation: string }[] = [
  {
    name: "Alabama",
    abbreviation: "AL",
  },
  {
    name: "Alaska",
    abbreviation: "AK",
  },
  {
    name: "American Samoa",
    abbreviation: "AS",
  },
  {
    name: "Arizona",
    abbreviation: "AZ",
  },
  {
    name: "Arkansas",
    abbreviation: "AR",
  },
  {
    name: "California",
    abbreviation: "CA",
  },
  {
    name: "Colorado",
    abbreviation: "CO",
  },
  {
    name: "Connecticut",
    abbreviation: "CT",
  },
  {
    name: "Delaware",
    abbreviation: "DE",
  },
  {
    name: "District Of Columbia",
    abbreviation: "DC",
  },
  {
    name: "Federated States Of Micronesia",
    abbreviation: "FM",
  },
  {
    name: "Florida",
    abbreviation: "FL",
  },
  {
    name: "Georgia",
    abbreviation: "GA",
  },
  {
    name: "Guam",
    abbreviation: "GU",
  },
  {
    name: "Hawaii",
    abbreviation: "HI",
  },
  {
    name: "Idaho",
    abbreviation: "ID",
  },
  {
    name: "Illinois",
    abbreviation: "IL",
  },
  {
    name: "Indiana",
    abbreviation: "IN",
  },
  {
    name: "Iowa",
    abbreviation: "IA",
  },
  {
    name: "Kansas",
    abbreviation: "KS",
  },
  {
    name: "Kentucky",
    abbreviation: "KY",
  },
  {
    name: "Louisiana",
    abbreviation: "LA",
  },
  {
    name: "Maine",
    abbreviation: "ME",
  },
  {
    name: "Marshall Islands",
    abbreviation: "MH",
  },
  {
    name: "Maryland",
    abbreviation: "MD",
  },
  {
    name: "Massachusetts",
    abbreviation: "MA",
  },
  {
    name: "Michigan",
    abbreviation: "MI",
  },
  {
    name: "Minnesota",
    abbreviation: "MN",
  },
  {
    name: "Mississippi",
    abbreviation: "MS",
  },
  {
    name: "Missouri",
    abbreviation: "MO",
  },
  {
    name: "Montana",
    abbreviation: "MT",
  },
  {
    name: "Nebraska",
    abbreviation: "NE",
  },
  {
    name: "Nevada",
    abbreviation: "NV",
  },
  {
    name: "New Hampshire",
    abbreviation: "NH",
  },
  {
    name: "New Jersey",
    abbreviation: "NJ",
  },
  {
    name: "New Mexico",
    abbreviation: "NM",
  },
  {
    name: "New York",
    abbreviation: "NY",
  },
  {
    name: "North Carolina",
    abbreviation: "NC",
  },
  {
    name: "North Dakota",
    abbreviation: "ND",
  },
  {
    name: "Northern Mariana Islands",
    abbreviation: "MP",
  },
  {
    name: "Ohio",
    abbreviation: "OH",
  },
  {
    name: "Oklahoma",
    abbreviation: "OK",
  },
  {
    name: "Oregon",
    abbreviation: "OR",
  },
  {
    name: "Palau",
    abbreviation: "PW",
  },
  {
    name: "Pennsylvania",
    abbreviation: "PA",
  },
  {
    name: "Puerto Rico",
    abbreviation: "PR",
  },
  {
    name: "Rhode Island",
    abbreviation: "RI",
  },
  {
    name: "South Carolina",
    abbreviation: "SC",
  },
  {
    name: "South Dakota",
    abbreviation: "SD",
  },
  {
    name: "Tennessee",
    abbreviation: "TN",
  },
  {
    name: "Texas",
    abbreviation: "TX",
  },
  {
    name: "Utah",
    abbreviation: "UT",
  },
  {
    name: "Vermont",
    abbreviation: "VT",
  },
  {
    name: "Virgin Islands",
    abbreviation: "VI",
  },
  {
    name: "Virginia",
    abbreviation: "VA",
  },
  {
    name: "Washington",
    abbreviation: "WA",
  },
  {
    name: "West Virginia",
    abbreviation: "WV",
  },
  {
    name: "Wisconsin",
    abbreviation: "WI",
  },
  {
    name: "Wyoming",
    abbreviation: "WY",
  },
]
